[package]
name = "tpm2"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mem_macros = "1.0.0"
bincode = "1.2.1"
bytebuffer = "0.2.0"
hex = "0.4"

